### ISSUE TITLE
should unused opcodes be removed?

### ISSUE THREAD

**Issue by disaderp** [disaderp/automatic-chainsaw#15]

**Comment by logarytm** [comment]
But what?

**Comment by disaderp** [comment]
unused by compilator CPU operation (for better performance/smaller LUT usage)

**Comment by logarytm** [comment]
Sure, why not?

**Comment by logarytm** [comment]
Programatically generated list of unused commands:

```
cff
cof
czf
div6
div8
in
mul6
mul8
nop
scf
shl
xch
```

Note however that some are essential to the insrtuction set, just not exposed to C-- (like `IN`/`OUT`).

**Comment by disaderp** [comment]
great, add `shl` as operator in compiler

**Comment by logarytm** [comment]
Added in https://github.com/disaderp/automatic-chainsaw/commit/95f1d4058bdd3d8397217b7c3ba7c7b2ac84325f.

**Comment by disaderp** [comment]
moved to #29
