### ISSUE TITLE
Add Travis ci/appveyor for all subprojects

### ISSUE THREAD

**Issue by disaderp** [disaderp/automatic-chainsaw#18]

**Comment by logarytm** [comment]
Could you expand what build steps are desired for each subproject? (besides the compiler)

**Comment by disaderp** [comment]
- ASM: `mono vbc` (for linux) or `vbc` for windows
- CPU: example for windows: `C:\Users\Karol\Documents\Visual Studio 2013\Projects\automatic-chainsaw\SIMULATOR>c:\iverilog\bin\iverilog -Wall -g2012 -s CPU -o tmp\compiled.vvp ..\CPU\ALU.v
..\CPU\Buff.v ..\CPU\SDCard.v ..\CPU\RAM.v ..\CPU\CPU.v`
- GPU: `C:\Users\Karol\Documents\Visual Studio 2013\Projects\automatic-chainsaw\SIMULATOR>c:\iverilog\bin\iverilog -Wall -g2012 -s GPU -o tmp\compiled.vvp ..\GPU\Font_ROM.v ..\GPU\TXT.v ..\GPU\VGA.v ..\GPU\GPU.v`
- OS: compile `main.c` using compiler
- SIM: (maybe) check syntax?
